import time
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont
from reelforge.agents.base import BaseAgent
from reelforge.config import settings, IMAGES_DIR
from reelforge.models import JobState, ScriptSegment


class VisualAgent(BaseAgent):
    """
    F7 - Visual Generation Agent
    Renders styled 9:16 graphic slide assets (1080x1920) for script sections.
    """
    
    def __init__(self):
        super().__init__("VisualAgent")

    def execute(self, state: JobState) -> JobState:
        if not state.script:
            raise ValueError("Script state missing for VisualAgent execution.")

        self.log(state, "Generating 9:16 visual slide assets for Reel script...")

        generated_paths = []
        for idx, segment in enumerate(state.script.segments):
            # Skip DEMO segment if terminal card was already generated by CodeAgent
            if segment.section == "DEMO" and state.code_result and state.code_result.output_image_path:
                continue
                
            slide_path = self.render_slide(segment, idx)
            generated_paths.append(slide_path)

        state.visual_paths.extend(generated_paths)
        self.log(state, f"Generated {len(generated_paths)} high-res 9:16 visual slide cards.")
        return state

    def render_slide(self, segment: ScriptSegment, index: int) -> str:
        w, h = settings.VIDEO_WIDTH, settings.VIDEO_HEIGHT
        img = Image.new("RGBA", (w, h), (12, 16, 26, 255))
        draw = ImageDraw.Draw(img)

        # Dynamic gradient background based on section
        section_colors = {
            "HOOK": ((20, 25, 45), (10, 15, 30), (0, 230, 150)),
            "PROBLEM": ((35, 15, 20), (20, 10, 15), (255, 80, 80)),
            "EXPLANATION": ((15, 25, 40), (10, 15, 25), (80, 180, 255)),
            "RESULT": ((15, 35, 25), (10, 20, 15), (40, 220, 120)),
            "CTA": ((25, 20, 45), (15, 10, 30), (220, 100, 255))
        }

        top_color, bot_color, accent = section_colors.get(segment.section, ((15, 20, 30), (10, 12, 20), (0, 230, 150)))

        for y in range(h):
            factor = y / h
            r = int(top_color[0] * (1 - factor) + bot_color[0] * factor)
            g = int(top_color[1] * (1 - factor) + bot_color[1] * factor)
            b = int(top_color[2] * (1 - factor) + bot_color[2] * factor)
            draw.line([(0, y), (w, y)], fill=(r, g, b, 255))

        # Fonts
        try:
            font_badge = ImageFont.truetype("arial.ttf", 26)
            font_main = ImageFont.truetype("arialbd.ttf", 46)
            font_sub = ImageFont.truetype("arial.ttf", 32)
            font_footer = ImageFont.truetype("arial.ttf", 24)
        except Exception:
            font_badge = ImageFont.load_default()
            font_main = ImageFont.load_default()
            font_sub = ImageFont.load_default()
            font_footer = ImageFont.load_default()

        # Header Badge
        badge_text = f"  {segment.section}  "
        draw.rounded_rectangle([60, 180, 320, 240], radius=15, fill=(*accent, 40), outline=(*accent, 255), width=2)
        draw.text((80, 195), badge_text, fill=(255, 255, 255, 255), font=font_badge)

        # Central Card Container (960x1000)
        card_margin_x = 60
        card_margin_y = 360
        card_w = w - (card_margin_x * 2)
        card_h = 1000

        draw.rounded_rectangle(
            [card_margin_x, card_margin_y, card_margin_x + card_w, card_margin_y + card_h],
            radius=24,
            fill=(22, 28, 42, 230),
            outline=(45, 55, 75, 255),
            width=2
        )

        # Draw Wrapped Text inside card
        text_y = card_margin_y + 120
        words = segment.narration.split()
        lines = []
        current_line = []

        for word in words:
            current_line.append(word)
            test_str = " ".join(current_line)
            if len(test_str) > 28:
                current_line.pop()
                lines.append(" ".join(current_line))
                current_line = [word]
        if current_line:
            lines.append(" ".join(current_line))

        for line in lines[:8]:
            draw.text((card_margin_x + 50, text_y), line, fill=(240, 245, 255, 255), font=font_main)
            text_y += 65

        # Visual Prompt Description
        draw.text((card_margin_x + 50, card_margin_y + card_h - 100), f"⚡ {segment.visual_prompt}", fill=(*accent, 255), font=font_sub)

        # Footer Branding
        draw.text((w // 2 - 140, h - 140), f"{settings.BRAND_NAME} | {settings.INSTAGRAM_HANDLE}", fill=(130, 150, 180, 220), font=font_footer)

        output_filename = f"slide_{index}_{segment.section}_{int(time.time())}.png"
        output_path = str(IMAGES_DIR / output_filename)
        img.save(output_path, "PNG")
        return output_path

